
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mysecretkey
  expiration: 3600000
  refresh-expiration: 604800000
